### PR TITLE
Feature/remove null level segments

### PR DESCRIPTION
**Pull request by catalinzpop**

### CODE REVIEW

**Comment by brentlintner** [comment]
[Ensure that there are no "Stress Level: null" way segments in our routing data](https://trello.com/c/Fjf7PkI0/183-ensure-that-there-are-no-stress-level-null-way-segments-in-our-routing-data)

**Review by brentlintner — APPROVED** [review]
Took a look at the diffs, LGTM!

I also plan to run through this with the CLI and the `-t` option as mentioned to see if I notice anything. I am less familiar with the data stuff still though, so maybe someone else can too! 😄

**Comment by brentlintner** [comment]
[Split Stress Level 0 to separate highways and sidewalks](https://trello.com/c/kFKCKFN0/182-split-stress-level-0-to-separate-highways-and-sidewalks)

**Review by peterspenler — APPROVED** [review]
LGTM

**Pull request merged**
