### PR TITLE
Changed max speed from 70 to 80

### PR DESCRIPTION
**Pull request by JacksonZeitspace**

### CODE REVIEW

**Comment by brentlintner** [comment]
[LTS undefined for unclassified maxspeed=80](https://trello.com/c/wXBP18C0/847-lts-undefined-for-unclassified-maxspeed80)

**Review by brentlintner — COMMENTED** [review]
The commit message should say why it was fixed not what. The diffs already convey that.

For example: `The LTS gets set to undefined when maxspeed=80`.

This is also good for posterity, for when people read the history or use git blame they can understand why the change happened, without having to infer from the diffs themselves.

**Comment by JacksonZeitspace** [comment]
> The commit message should say why it was fixed not what. The diffs already convey that.
> 
> For example: `The LTS gets set to undefined when maxspeed=80`.
> 
> This is also good for posterity, for when people read the history or use git blame they can understand why the change happened, without having to infer from the diffs themselves.

I actually disagree with this. The one I have could be better but I would change it from `Changed max speed from 70 to 80` to `Change max speed from 70 to 80 for unclassified roads` to improve it.

Having the commit message be the original problem is more confusing than seeing what the commit message did as to me it looks like now the behaviour should be setting it to undefined when maxspeed=80 in your example

**Comment by JacksonZeitspace** [comment]
At some of my old jobs, the convention was to make it human readable and describe what the commit does by pretending a commit starts with the sentence "This commit will" and then write the commit message

**Review by StevenPicache — APPROVED** [review]
lgtm

**Comment by brentlintner** [comment]
> > The commit message should say why it was fixed not what. The diffs already convey that.
> > For example: `The LTS gets set to undefined when maxspeed=80`.
> > This is also good for posterity, for when people read the history or use git blame they can understand why the change happened, without having to infer from the diffs themselves.
> 
> I actually disagree with this. The one I have could be better but I would change it from `Changed max speed from 70 to 80` to `Change max speed from 70 to 80 for unclassified roads` to improve it.
> 
> Having the commit message be the original problem is more confusing than seeing what the commit message did as to me it looks like now the behaviour should be setting it to undefined when maxspeed=80 in your example

Yeah in hindsight my example didn't make as much sense. The important point I wanted to make is that a commit message should ideally explain why something is being done, not just what. I.e Why did you change the max speed from 70 to 80?

**Comment by brentlintner** [comment]
> At some of my old jobs, the convention was to make it human readable and describe what the commit does by pretending a commit starts with the sentence "This commit will" and then write the commit message

That's cool. If anything being human readable and like a sentence or subject. But I disagree on it describing what it does, vs describing why it does.

Although alas that prefix makes the already stupid shortness requirements harder 🤪. Tbh I wish the message length rule of thumb was longer... 😐

**Pull request merged**
